services:
  # Base de datos para el Microservicio de Clientes
  db_customer:
    image: postgres:15
    container_name: banking-db-customer
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_customer_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data
      - ./ms-customer/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  #Base de datos para el Microservicio de Cuentas
  db_account:
    image: postgres:15
    container_name: banking-db-account
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_account_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_account:/var/lib/postgresql/data
      - ./ms-account/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Base de datos para el Microservicio de Transacciones
  db_transaction:
    image: postgres:15
    container_name: banking-db-transaction
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_transaction_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_transaction:/var/lib/postgresql/data
      - ./ms-transaction/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Base de datos para el Microservicio de Préstamos
  db_loan:
    image: postgres:15
    container_name: banking-db-loan
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_loan_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_loan:/var/lib/postgresql/data
      - ./ms-loan/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Base de datos para el Microservicio de Logística
  db_logistics:
    image: postgres:15
    container_name: banking-db-logistics
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_logistics_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432" # Puerto 5437 para no chocar
    volumes:
      - postgres_data_logistics:/var/lib/postgresql/data
      - ./ms-logistics/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Administrador Visual de todas las bases de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: banking-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banking.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db_customer
      - db_account
      - db_transaction
    networks:
      - banking-network

  # Infraestructura
  ms-config-server:
    build:
      context: ./ms-config-server
      dockerfile: Dockerfile
    container_name: banking-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - PROPERTIES_DIRECTORY=/app/config-repo
    volumes:
      - ./banking-config-repo:/app/config-repo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - banking-network

  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    container_name: banking-registry-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # Le decimos al microservicio dónde encontrar al Config Server dentro de la red de Docker
      - SPRING_CONFIG_IMPORT=configserver:http://admin:local123@banking-config-server:8888
    depends_on:
      ms-config-server:
        condition: service_healthy
    networks:
      - banking-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: banking-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # IMPORTANTE: Cambiamos localhost por los nombres de los contenedores
      - SPRING_CLOUD_CONFIG_URI=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
    depends_on:
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-customer:
    build:
      context: ./ms-customer
      dockerfile: Dockerfile
    container_name: banking-ms-customer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://banking-db-customer:5432/db_customer_dev
    depends_on:
      db_customer:
        condition: service_healthy
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-account:
    build:
      context: ./ms-account
      dockerfile: Dockerfile
    container_name: banking-ms-account
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://banking-db-account:5432/db_account_dev
    depends_on:
      db_account:
        condition: service_healthy
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-transaction:
    build:
      context: ./ms-transaction
      dockerfile: Dockerfile
    container_name: banking-ms-transaction
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://banking-db-transaction:5432/db_transaction_dev
    depends_on:
      db_transaction:
        condition: service_healthy
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-loan:
    build:
      context: ./ms-loan
      dockerfile: Dockerfile
    container_name: banking-ms-loan
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://banking-db-loan:5432/db_loan_dev
    depends_on:
      db_loan:
        condition: service_healthy
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-logistics:
    build:
      context: ./ms-logistics
      dockerfile: Dockerfile
    container_name: banking-ms-logistics
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://banking-db-logistics:5432/db_logistics_dev
    depends_on:
      db_logistics:
        condition: service_healthy
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

  ms-report:
    build:
      context: ./ms-report
      dockerfile: Dockerfile
    container_name: banking-ms-report
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://admin:local123@banking-config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://banking-registry-service:8761/eureka/
    depends_on:
      ms-config-server:
        condition: service_healthy
      registry-service:
        condition: service_started
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data_customer:
  postgres_data_account:
  postgres_data_transaction:
  postgres_data_loan:
  postgres_data_logistics:
