services:
  # Base de datos para el Microservicio de Clientes
  db_customer:
    image: postgres:15
    container_name: banking-db-customer
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_customer_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data
      - ./ms-customer/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  #Base de datos para el Microservicio de Cuentas
  db_account:
    image: postgres:15
    container_name: banking-db-account
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_account_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_account:/var/lib/postgresql/data
      - ./ms-account/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Base de datos para el Microservicio de Transacciones
  db_transaction:
    image: postgres:15
    container_name: banking-db-transaction
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_transaction_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_transaction:/var/lib/postgresql/data
      - ./ms-transaction/database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Administrador Visual de todas las bases de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: banking-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banking.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db_customer
      - db_account
      - db_transaction
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data_customer:
  postgres_data_account:
  postgres_data_transaction:
